### PR TITLE
Minor correction to Waldo's AccountMultiView

### PR DESCRIPTION
**Pull request by harrislapiroff**
This should be request.node rather than node.

### CODE REVIEW

**Comment by melinath** [comment]
Should this be pulled into master or develop? I think it mostly depends on the time frame before the next release. If we're planning on releasing 1.0 soon, it might as well just wait. Or we could have some way of having blessed point release branches containing this kind of bugfix (a la django's 1.3.X branch.)

**Comment by harrislapiroff** [comment]
My personal opinion is that it is a hotfix, which would actively prevent a particular philo setup (i.e., a site with an AccountMultiView that does not specify a manage account page) from functioning and which is small enough that it apparently does not introduce any bugs, and therefore should be pulled into master.

**Comment by melinath** [comment]
I should clarify that I was mostly wondering because right now we don't really have a release policy. According to our branch model, pulling a hotfix would require a new release. If the hotfix were to be pulled into master, then my 0.9.X branch could be pulled in as well - perhaps being merged into a release branch first. However, if we're about to release 1.0 anyway, is it worth doing a hotfix release?

**Comment by jspiros** [comment]
I'm not too worried about hotfix releases right now, as pre-1.0 releases are inherently beta, in my opinion. But, yes, indeed, if you want to create a hotfix, then base it on the latest commit on the master branch, not off of commits in the develop branch, so it won't bring other things in. And then we'll merge it into the develop and master branches simultaneously.

**Comment by jspiros** [comment]
Er, sorry, I'm confused. You created the hotfix correctly, but I would request that you ask me to pull a branch named something-hotfix, and then I'll merge it into master if/when ready to do a release. The way it is right now, I'm just going to merge it into develop.

**Pull request closed without merging**
